name: Data-Imputation-Thesis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.*
  - pip
  - numpy
  - scipy
  - pandas
  - ipython
  - matplotlib
  - seaborn
  - scikit-learn>=0.24
  - optuna
  # for development only (could also be kept in a separate environment file)
  - pip:
    - flake8
    - autokeras
    - flake8-mypy
    - pydocstyle
    - tensorflow==2.10 #2.10 / tensorflow-text==2.10
    - tensorflow-text==2.10
    - openml
    - typer
    - plotly==5.14.1
#    - rope
    - jedi==0.17.2 # https://github.com/ipython/ipython/issues/12740
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - sphinx
  - recommonmark
